#!/bin/bash

if [[ -n "${TOOLSET}" ]] &&  [[ "${TOOLSET}" != "gcc" ]]; then
        echo "TOOLSET is set to '${TOOLSET}' - skipping compilation of gmp" 1>&2
        exit 0
fi

# recipe for:
P=gmp
V=${GMP_VERSION:-6.1.2}

FNAME="$P-$V.tar.bz2"
DOWNLOAD_URL="https://gmplib.org/download/$P/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --disable-shared

# compile and install
make -j ${NJOBS}
make install

