#!/bin/bash

# recipe for:
P=gmp
V=${GMP_VERSION:-6.1.2}

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.bz2" || \
        curl -L \
                --output "$_" \
                "https://gmplib.org/download/$P/$P-$V.tar.bz2"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --disable-shared

# compile and install
make -j ${NJOBS}
make install

