#!/bin/bash
#
# OPAL Toolchain Build recipe to build the GNU MPFR Library.
#
# https://www.mpfr.org
#
P=mpfr
V=${MPFR_VERSION:=4.1.0}

trap "otb_exit" EXIT

if [[ -n "${OTB_TOOLSET}" ]] &&  [[ "${OTB_TOOLSET}" != "gcc" ]]; then
        echo "TOOLSET is set to '${OTB_TOOLSET}' - skipping compilation of mpfr" 1>&2
        exit 0
fi

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://www.mpfr.org/$P-$V/$P-$V.tar.gz"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
mkdir -p "${OTB_DOWNLOAD_DIR}"
test -r "${SRC_FILE}" || \
    curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

# configure
mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
"${OTB_SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${OTB_PREFIX}" \
        --with-gmp="${OTB_PREFIX}" \
        --disable-shared || exit ${OTB_ERR_CONFIGURE}

# compile & install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:


