#!/bin/bash

# recipe for:
P=mpfr
V=${MPFR_VERSION:=4.0.1}

DOWNLOAD_URL="http://www.mpfr.org/$P-$V/$P-$V.tar.gz"

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
	curl -L --output "$_" "${DOWNLOAD_URL}" 

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install

