#!/bin/bash

if [[ -n "${TOOLSET}" ]] &&  [[ "${TOOLSET}" != "gcc" ]]; then
        echo "TOOLSET is set to '${TOOLSET}' - skipping compilation of mpfr" 1>&2
        exit 0
fi

# recipe for:
P=mpfr
V=${MPFR_VERSION:=4.0.1}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://www.mpfr.org/$P-$V/$P-$V.tar.gz"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}" 

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install

