#!/bin/bash

if [[ -n "${TOOLSET}" ]] &&  [[ "${TOOLSET}" != "gcc" ]]; then
        echo "TOOLSET is set to '${TOOLSET}' - skipping compilation of mpc" 1>&2
        exit 0
fi

# recipe for:
P=mpc
V=${MPC_VERSION:-1.1.0}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="ftp://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --with-mpfr="${PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install
