#!/bin/bash
#
# OPAL Toolchain Build recipe for GNU MPC Library.
#
# home: http://www.multiprecision.org/mpc
# download: https://ftp.gnu.org/gnu/mpc/
#
P=mpc
V=${MPC_VERSION:-1.3.1}

trap "otb_exit" EXIT

if [[ -n "${OTB_TOOLSET}" ]] &&  [[ "${OTB_TOOLSET}" != "gcc" ]]; then
        echo "TOOLSET is set to '${OTB_TOOLSET}' - skipping compilation of mpc" 1>&2
        exit 0
fi

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

if [[ "${OTB_OS}" == 'Linux' ]]; then
	read OS_ID OS_VERSION < <(bash -c 'source /etc/os-release; printf "%s %s\n" $ID $VERSION')
	if [[ "${OS_ID}" == 'opensuse-leap' ]]; then
       		case "${OS_VERSION}" in
	        	16.0 )
		  		CC='/usr/bin/gcc-13'
		       		CXX='/usr/bin/g++-13'
		        	;;
			* )
		  		CC='/usr/bin/gcc'
		       		CXX='/usr/bin/g++'
				;;
		esac
		export CC CXX
	fi
fi

# download
mkdir -p "${OTB_DOWNLOAD_DIR}"
test -r "${SRC_FILE}" || \
    curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${OTB_SRC_DIR}/$P/build-$V" && cd "$_"
"${OTB_SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${OTB_PREFIX}" \
        --with-gmp="${OTB_PREFIX}" \
        --with-mpfr="${OTB_PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

