#!/bin/bash

# recipe for:
P=gcc
V=${GCC_VERSION:-7.3.0}

DOWNLOAD_URL="https://ftp.gnu.org/gnu/$P/$P-$V/$P-$V.tar.gz"

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L --output "$_" "${DOWNLOAD_URL}"

# GCC on Linux tries to create the directory $PREFIX/lib64.
# So 'make install' fails, if this is a sym-link.
rm -v "${PREFIX}/lib64"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --with-mpfr="${PREFIX}" \
        --with-mpc="${PREFIX}" \
        --enable-languages=c,c++,objc,obj-c++,lto,fortran \
        --enable-lto \
        --disable-multilib \
        --with-build-config=bootstrap-debug



# compile & install
make -j 2
make install

# move files from "${PREFIX}/lib64" to "${PREFIX}/lib"
# and recreate sym-link
shopt -s nullglob
if [[ -n "${PREFIX}/lib64/*" ]]; then
	mv -v  "${PREFIX}/lib64/"*  "${PREFIX}/lib"
	rmdir "${PREFIX}/lib64"
fi
( cd $PREFIX; ln -s lib lib64;)

