#!/bin/bash

# recipe for:
P=gcc
V=${GCC_VERSION:-7.3.0}

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L \
                --output "$_" \
                "https://ftp.gnu.org/gnu/$P/$P-$V/$P-$V.tar.gz"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --with-mpfr="${PREFIX}" \
        --with-mpc="${PREFIX}" \
        --enable-languages=c,c++,objc,obj-c++,lto,fortran \
        --enable-lto \
        --disable-multilib \
        --with-build-config=bootstrap-debug

# compile & install
make -j ${NJOBS}
make install

