#!/bin/bash

# recipe for:
P=gcc
V=${GCC_VERSION:-7.3.0}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="https://ftp.gnu.org/gnu/$P/$P-$V/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

# GCC on Linux tries to create the directory $PREFIX/lib64.
# So 'make install' fails, if this is a sym-link.
if [[ $(uname -s) == Linux ]]; then
	rm -v "${PREFIX}/lib64"
fi

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --with-mpfr="${PREFIX}" \
        --with-mpc="${PREFIX}" \
        --enable-languages=c,c++,objc,obj-c++,lto,fortran \
        --enable-lto \
        --disable-multilib \
        --with-build-config=bootstrap-debug

# compile & install
make -j 2
make install

# move files from "${PREFIX}/lib64" to "${PREFIX}/lib"
# and recreate sym-link
shopt -s nullglob
if [[ $(uname -s) == Linux ]]; then
	mv -v  "${PREFIX}/lib64/"*  "${PREFIX}/lib"
	rmdir "${PREFIX}/lib64"
	( cd $PREFIX; ln -s lib lib64;)
fi
