#!/bin/bash
#
# OPAL Toolchain Build recipe for CMake
#
# https://cmake.org
#
P=cmake
V=${CMAKE_VERSION:-3.22.1}

trap "otb_exit" EXIT

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="https://cmake.org/files/v${V%.*}/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

#
# Download
#
mkdir -p "${OTB_DOWNLOAD_DIR}"
test -r "${SRC_FILE}" || \
    curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

#
# Unpack
#
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

#
# Configure
# You might have to add the option --system-curl
#
mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
"${OTB_SRC_DIR}/cmake/cmake-$V/bootstrap" \
        --prefix="${OTB_PREFIX}" \
	--no-system-libs \
	--parallel=${NJOBS} \
        --verbose \
	-- \
	-DCMAKE_USE_OPENSSL=OFF \
       || exit ${OTB_ERR_CONFIGURE}
#
# Compile and install CMake
#
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

