#!/bin/bash
#
# Recipe for
#
P=cmake
V=${CMAKE_VERSION:-3.11.4}

DOWNLOAD_URL="https://cmake.org/files/v${V%.*}/$P-$V.tar.gz"

#
# Download
#
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L --output "$_" ${DOWNLOAD_URL}"

#
# Unpack
#
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

#
# Configure
# You might have to add the option --system-curl
#
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/cmake/cmake-$V/bootstrap" \
        --prefix="${PREFIX}" \
        --verbose
#
# Compile and install CMake
#
make -j ${NJOBS}
make install

