#!/bin/bash
#
# Recipe for
#
P=cmake
V=${CMAKE_VERSION:-3.15.5}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="https://cmake.org/files/v${V%.*}/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

#
# Download
#
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

#
# Unpack
#
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

#
# Configure
# You might have to add the option --system-curl
#
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/cmake/cmake-$V/bootstrap" \
        --prefix="${PREFIX}" \
        --verbose
#
# Compile and install CMake
#
make -j ${NJOBS}
make install

