#!/bin/bash

if [[ -n "${MPI_IMPLEMENTATION}" ]] && [[ "${MPI_IMPLEMENTATION}" != "openmpi" ]]; then
        echo "MPI implementation is set to '${MPI_IMPLEMENTATION}' - skipping compilation of openmpi" 1>&2
	exit 0
fi

# recipe for:
P=openmpi
V=${OPENMPI_VERSION:-3.1.6}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://www.open-mpi.org/software/ompi/v${V%.*}/downloads/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# Download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${BUILD_ERR_DOWNLOAD}

# Unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_" || exit ${BUILD_ERR_SETUP}
tar xvf "${SRC_FILE}" || exit ${BUILD_ERR_UNTAR}

# Configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_" || exit ${BUILD_ERR_SETUP}
"${SRC_DIR}/$P/$P-$V/configure" \
                --prefix="${PREFIX}" \
                --enable-mpi-cxx \
                --enable-mpi-cxx-seek \
                --enable-orterun-prefix-by-default \
                --enable-shared \
                --with-sge=yes \
                --with-slurm=yes || exit ${BUILD_ERR_CONFIGURE}

# Compile and install
make -j ${NJOBS} || exit ${BUILD_ERR_MAKE}
make install || exit ${BUILD_ERR_INSTALL}

