#!/bin/bash

# recipe for:
P=openmpi
V=${OPENMPI_VERSION:-3.1.3}

DOWNLOAD_URL="http://www.open-mpi.org/software/ompi/v${V%.*}/downloads/$P-$V.tar.bz2"

# Download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.bz2" || \
        curl -L --output "$_" "${DOWNLOAD_URL}"

# Unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"

# Configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
                --prefix="${PREFIX}" \
                --enable-mpi-cxx \
                --enable-mpi-cxx-seek \
                --enable-mpi-profile \
                --enable-orterun-prefix-by-default \
                --enable-shared \
                --enable-smp-locks \
                --with-sge=yes \
                --with-slurm=yes

# Compile and install
make -j ${NJOBS}
make install

