#!/bin/bash

# recipe for:
P=hdf5
V=${HDF5_VERSION:-1.10.3}

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.bz2"  ||
        curl -L \
                --output "$_" \
                "https://support.hdfgroup.org/ftp/HDF5/releases/$P-${V%.*}/$P-$V/src/$P-$V.tar.bz2"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx FC=mpifort "${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --enable-cxx \
        --enable-unsupported \
        --with-pic

# compile and install
make -j ${NJOBS}
make install

