#!/bin/bash

# recipe for:
P=gsl
V=${GSL_VERSION:-2.5}

DOWNLOAD_URL="ftp://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
                --prefix="${PREFIX}" \
                --disable-shared

# compile & install
make -j ${NJOBS}
make install

