#!/bin/bash

# recipe for:
P=H5hut
V=${H5HUT_VERSION:-2.0.0rc4}

DOWNLOAD_URL="http://amas.web.psi.ch/Downloads/$P/$P-$V.tar.gz"

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L --output "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx "${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --with-pic

# compile and install
make -j ${NJOBS}
make install

