#!/bin/bash

# recipe for:
P=zlib
V=${ZLIB_VERSION:-1.2.11}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="https://zlib.net/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \

# compile & install
make -j ${NJOBS}
make install
