#!/bin/bash

# recipe for:
P=boost
V=${BOOST_VERSION:-1_70_0}

FNAME="${P}_$V.tar.gz"
DOWNLOAD_URL="https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

test -n "${TOOLSET}" || TOOLSET='gcc'

# download
test -r "${SRC_FILE}"  || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${BUILD_ERR_DOWNLOAD}

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_" || exit ${BUILD_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${BUILD_ERR_UNTAR}
cd "${SRC_DIR}/$P/${P}_$V" || exit ${BUILD_ERR_CONFIGURE}
patch -p1 <<EOF
--- src.orig/libs/context/build/Jamfile.v2	2018-08-01 22:50:46.000000000 +0200
+++ src/libs/context/build/Jamfile.v2	2018-11-30 10:06:57.000000000 +0100
@@ -613,6 +613,17 @@
      <address-model>64
      <architecture>x86
      <binary-format>mach-o
+     <toolset>gcc
+   ;
+
+alias asm_sources
+   : asm/make_x86_64_sysv_macho_gas.S
+     asm/jump_x86_64_sysv_macho_gas.S
+     asm/ontop_x86_64_sysv_macho_gas.S
+   : <abi>sysv
+     <address-model>64
+     <architecture>x86
+     <binary-format>mach-o
      <toolset>darwin
    ;
EOF
[[ $? == 0 ]] || exit ${BUILD_ERR_CONFIGURE}

# configure
mkdir -p "${SRC_DIR}/$P/build" || exit ${BUILD_ERR_SYSTEM}
cd "${SRC_DIR}/$P/${P}_$V"  || exit ${BUILD_ERR_SYSTEM}
./bootstrap.sh \
        --prefix="${PREFIX}" \
        --with-toolset=${TOOLSET} \
        --without-libraries=python \
        || exit 1 || exit ${BUILD_ERR_CONFIGURE}
        echo "using mpi ;" >> "./project-config.jam" || exit ${BUILD_ERR_CONFIGURE}

# compile & install
./b2 \
        --build-dir="${BUILD_DIR}" \
        --layout=system \
        --without-python \
        toolset=${TOOLSET} \
        variant=release \
        link=shared,static \
        threading=multi \
        install -j 3 \
        || exit ${BUILD_ERR_INSTALL}
