#!/bin/bash
#
# OPAL Toolset Build recipe for Boost
#
# https://www.boost.org
P=boost
V=${BOOST_VERSION:-1_84_0}

trap "otb_exit" EXIT

FNAME="${P}_$V.tar.gz"
DOWNLOAD_URL="https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
mkdir -p "${OTB_DOWNLOAD_DIR}"
test -r "${SRC_FILE}"  || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}
cd "${OTB_SRC_DIR}/$P/${P}_$V" || exit ${OTB_ERR_CONFIGURE}

# apply patch for macOS
patch -p1 <<EOF
--- src.orig/libs/context/build/Jamfile.v2	2018-08-01 22:50:46.000000000 +0200
+++ src/libs/context/build/Jamfile.v2	2018-11-30 10:06:57.000000000 +0100
@@ -613,6 +613,17 @@
      <address-model>64
      <architecture>x86
      <binary-format>mach-o
+     <toolset>gcc
+   ;
+
+alias asm_sources
+   : asm/make_x86_64_sysv_macho_gas.S
+     asm/jump_x86_64_sysv_macho_gas.S
+     asm/ontop_x86_64_sysv_macho_gas.S
+   : <abi>sysv
+     <address-model>64
+     <architecture>x86
+     <binary-format>mach-o
      <toolset>darwin
    ;
EOF
[[ $? == 0 ]] || exit ${OTB_ERR_CONFIGURE}

# configure
config_args=()
if [[ -n ${OTB_PYTHON_VERSION} ]]; then
        config_args+=( '--with-python=python3' )
        config_args+=( '--with-libraries=all' )
        config_args+=( "--with-python-version=${OTB_PYTHON_VERSION}" )
else
        config_args+=( '--without-python' )
fi

mkdir -p "${OTB_SRC_DIR}/$P/build" || exit ${OTB_ERR_SYSTEM}
cd "${OTB_SRC_DIR}/$P/${P}_$V"  || exit ${OTB_ERR_SYSTEM}
./bootstrap.sh \
        --prefix="${OTB_PREFIX}" \
        --with-toolset=${OTB_TOOLSET} \
        "${config_args[@]}" \
        || exit 1 || exit ${OTB_ERR_CONFIGURE}
        echo "using mpi ;" >> "./project-config.jam" || exit ${OTB_ERR_CONFIGURE}

# compile & install
./b2 \
        --prefix="${OTB_PREFIX}" \
        --build-dir="${BUILD_DIR}" \
        --layout=system \
        toolset=${OTB_TOOLSET} \
        variant=release \
        link=shared,static \
        threading=multi \
	cxxflags=-fPIC cflags=-fPIC \
        install -j 3 \
        || exit ${OTB_ERR_INSTALL}

# see https://github.com/boostorg/phoenix/pull/112/files
case ${BOOST_VERSION} in
	1_80_0|1_81_0 )
		cd "${OTB_PREFIX}/include/boost"
		patch -p1 <<EOF
--- boost.orig/phoenix/stl/tuple.hpp	2023-04-04 16:37:42
+++ boost/phoenix/stl/tuple.hpp	2023-04-04 16:27:59
@@ -110,7 +110,7 @@
     namespace placeholders {
         #define BOOST_PP_LOCAL_LIMITS (1, BOOST_PHOENIX_ARG_LIMIT)
         #define BOOST_PP_LOCAL_MACRO(N)                                                \
-            auto uarg##N =                                                             \
+            const auto uarg##N =                                                             \
             boost::phoenix::get_<(N)-1>(boost::phoenix::placeholders::arg1);
         #include BOOST_PP_LOCAL_ITERATE()
     }
EOF
		;;
esac
# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

