#!/bin/bash

# recipe for:
P=parmetis
V=${PARMETIS_VERSION:-4.0.3}

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="http://glaros.dtc.umn.edu/gkhome/fetch/sw/$P/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}"  || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
         -D CMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
         -D METIS_PATH="${SRC_DIR}/$P/$P-$V/metis" \
         -D GKLIB_PATH="${SRC_DIR}/$P/$P-$V/metis/GKlib" \
         "${SRC_DIR}/$P/$P-$V"

# compile and install
make -j ${NJOBS}
make install
install -m 0644 libmetis/libmetis.a "${PREFIX}/lib"
install -m 0644 "${SRC_DIR}/$P/$P-$V/metis/include/metis.h" "${PREFIX}/include"

