#!/bin/bash

# Please note:
# - The (experimental?) CMake script still has some issues.
# - You may try with other targets than CORE2. For auto-detection
#   just run make.

# recipe for:
P=OpenBLAS
V=${OPENBLAS_VERSION:-0.3.7}

FNAME="v$V.tar.gz"
DOWNLOAD_URL="http://github.com/xianyi/$P/archive/${FNAME}"
SRC_FILE="${DOWNLOADS_DIR}/$P-$V.tar.gz"

# download
test -r "${SRC_FILE}"  || curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${SRC_FILE}"
cd "$P-$V"

# configure
# nothing to configure

# compile & install
make TARGET=CORE2
make TARGET=CORE2 PREFIX="${PREFIX}" install
