#!/bin/bash
#
# OPAL Toolchain Build recipe for OpenBLAS
#
# http://www.openblas.net

# Please note:
# - The (experimental?) CMake script still has some issues.
# - You may try with other targets than CORE2. For auto-detection
#   just run make.

# recipe for:
P=OpenBLAS
V=${OPENBLAS_VERSION:-0.3.9}

trap "otb_exit" EXIT

FNAME="v$V.tar.gz"
DOWNLOAD_URL="http://github.com/xianyi/$P/archive/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/$P-$V.tar.gz"

# download
test -r "${SRC_FILE}"  || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}
cd "$P-$V" || exit ${OTB_ERR_SYSTEM}

# configure
# nothing to configure

# compile & install
make TARGET=CORE2 || exit ${OTB_ERR_MAKE}
make TARGET=CORE2 PREFIX="${OTB_PREFIX}" install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

