#!/bin/bash
#
# OPAL Toolchain Build recipe for Trilinos.
#
# https://trilinos.github.io
#
P=trilinos
V=${TRILINOS_VERSION:-13.2.0}

trap "otb_exit" EXIT

FNAME="$P-$V.tar.gz"
DOWNLOAD_URL="https://github.com/$P/$P/tarball/$P-release-${V//./-}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" || \
    curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P/src" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar -xv --strip-components 1 -f "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

# configure
OS=$(uname -s)
declare -a config_args=()
if [[ "${OS}" == "Linux" ]]; then
        config_args+=( "-DBLAS_LIBRARY_DIRS:PATH=${OTB_PREFIX}/lib" )
        config_args+=( "-DBLAS_INCLUDE_DIRS:PATH=${OTB_PREFIX}/include" )
        config_args+=( "-DBLAS_LIBRARY_NAMES:STRING=openblas" )
        config_args+=( "-DLAPACK_LIBRARY_DIRS:PATH=${OTB_PREFIX}/lib" )
        config_args+=( "-DLAPACK_INCLUDE_DIRS:PATH=${OTB_PREFIX}/include" )
        config_args+=( "-DLAPACK_LIBRARY_NAMES:STRING=openblas" )
        config_args+=( "-DCMAKE_Fortran_FLAGS:STRING=-fPIC" )
elif [[ "${OS}" == "Darwin" ]]; then
        config_args+=( "-DTrilinos_ENABLE_Fortran=OFF" )
	config_args+=( "-DCMAKE_CXX_FLAGS=-Wno-implicit-function-declaration" )
	config_args+=( "-DCMAKE_C_FLAGS=-Wno-implicit-function-declaration" )
fi

mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
CFLAGS="-Wno-error=implicit-function-declaration"
CC=mpicc CXX=mpicxx cmake \
	-DCMAKE_C_FLAGS="{CFLAGS}" \
	-DCMAKE_INSTALL_PREFIX:PATH="${OTB_PREFIX}" \
        -DCMAKE_CXX_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -DCMAKE_C_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -DCMAKE_BUILD_TYPE:STRING=Release \
	-DCMAKE_CXX_STANDARD=14 \
        -DTPL_ENABLE_DLlib:BOOL=OFF \
        -DTPL_ENABLE_QT:BOOL=OFF \
        -DTPL_ENABLE_MPI:BOOL=ON \
        -DTPL_ENABLE_BLAS:BOOL=ON \
        -DTPL_ENABLE_LAPACK:BOOL=ON \
        -DTPL_ENABLE_METIS:BOOL=ON \
        -DTPL_ENABLE_ParMETIS:BOOL=ON \
        -DTPL_METIS_INCLUDE_DIRS:PATH="${OTB_PREFIX}/include" \
        -DTPL_METIS_LIBRARIES:STRING="${OTB_PREFIX}/lib/libmetis.a" \
        -DTPL_ParMETIS_INCLUDE_DIRS:PATH="${OTB_PREFIX}/include" \
        -DTPL_ParMETIS_LIBRARIES:STRING="${OTB_PREFIX}/lib/libparmetis.a" \
        -DTrilinos_ENABLE_Amesos:BOOL=ON \
        -DTrilinos_ENABLE_Amesos2:BOOL=ON \
        -DTrilinos_ENABLE_AztecOO:BOOL=ON \
	-DAztecOO_DISABLE_STRONG_WARNINGS:BOOL=ON \
        -DTrilinos_ENABLE_Belos:BOOL=ON \
        -DTrilinos_ENABLE_Epetra:BOOL=ON \
        -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
        -DTrilinos_ENABLE_Galeri:BOOL=ON \
        -DTrilinos_ENABLE_Ifpack:BOOL=ON \
        -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
        -DTrilinos_ENABLE_Isorropia:BOOL=ON \
        -DTrilinos_ENABLE_Kokkos:BOOL=ON \
        -DTrilinos_ENABLE_ML:BOOL=ON \
        -DTrilinos_ENABLE_NOX:BOOL=ON \
	-DTrilinos_ENABLE_MueLu:BOOL=ON \
        -DTrilinos_ENABLE_Optika:BOOL=OFF \
        -DTrilinos_ENABLE_Teuchos:BOOL=ON \
        -DTrilinos_ENABLE_Tpetra:BOOL=ON \
	-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
        -DTrilinos_ENABLE_TESTS:BOOL=OFF \
        "${config_args[@]}" \
        "${OTB_SRC_DIR}/$P/src" || exit ${OTB_ERR_CONFIGURE}

# compile & install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

