#!/bin/bash

# recipe for:
P=trilinos
V=${TRILINOS_VERSION:-12.12.1}

DOWNLOAD_URL="https://github.com/$P/$P/tarball/$P-release-${V//./-}"

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L --output "$_" "${DOWNLOAD_URL}"

# unpack
mkdir -p "${SRC_DIR}/$P/src" && cd "$_"
tar -xv --strip-components 1 -f "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
OS=$(uname -s)
declare -a config_args=()
if [[ "${OS}" == "Linux" ]]; then
        config_args+=( "-DBLAS_LIBRARY_DIRS:PATH=${PREFIX}/lib" )
        config_args+=( "-DBLAS_INCLUDE_DIRS:PATH=${PREFIX}/include" )
        config_args+=( "-DBLAS_LIBRARY_NAMES:STRING=openblas" )
        config_args+=( "-DLAPACK_LIBRARY_DIRS:PATH=${PREFIX}/lib" )
        config_args+=( "-DLAPACK_INCLUDE_DIRS:PATH=${PREFIX}/include" )
        config_args+=( "-DLAPACK_LIBRARY_NAMES:STRING=openblas" )
        config_args+=( "-DCMAKE_Fortran_FLAGS:STRING=-fPIC" )
elif [[ "${OS}" == "Darwin" ]]; then
        config_args+=( "-DTrilinos_ENABLE_Fortran=OFF" )
fi

mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        -DCMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
        -DCMAKE_CXX_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -DCMAKE_C_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -DCMAKE_CXX_STANDARD:STRING="11" \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DTPL_ENABLE_DLlib:BOOL=OFF \
        -DTPL_ENABLE_QT:BOOL=OFF \
        -DTPL_ENABLE_MPI:BOOL=ON \
        -DTPL_ENABLE_BLAS:BOOL=ON \
        -DTPL_ENABLE_LAPACK:BOOL=ON \
        -DTPL_ENABLE_METIS:BOOL=ON \
        -DTPL_ENABLE_ParMETIS:BOOL=ON \
        -DTPL_METIS_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -DTPL_METIS_LIBRARIES:STRING="${PREFIX}/lib/libmetis.a" \
        -DTPL_ParMETIS_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -DTPL_ParMETIS_LIBRARIES:STRING="${PREFIX}/lib/libparmetis.a" \
        -DTrilinos_ENABLE_Amesos:BOOL=ON \
        -DTrilinos_ENABLE_Amesos2:BOOL=ON \
        -DTrilinos_ENABLE_AztecOO:BOOL=ON \
        -DTrilinos_ENABLE_Belos:BOOL=ON \
        -DTrilinos_ENABLE_Epetra:BOOL=ON \
        -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
        -DTrilinos_ENABLE_Galeri:BOOL=ON \
        -DTrilinos_ENABLE_Ifpack:BOOL=ON \
        -DTrilinos_ENABLE_Isorropia:BOOL=ON \
        -DTrilinos_ENABLE_ML:BOOL=ON \
        -DTrilinos_ENABLE_NOX:BOOL=ON \
        -DTrilinos_ENABLE_Optika:BOOL=OFF \
        -DTrilinos_ENABLE_Teuchos:BOOL=ON \
        -DTrilinos_ENABLE_Tpetra:BOOL=ON \
        -DTrilinos_ENABLE_TESTS:BOOL=OFF \
        "${config_args[@]}" \
        "${SRC_DIR}/$P/src"

# compile & install
make -j ${NJOBS}
make install

