#!/bin/bash
#
# OPAL Toolchain Build recipe for the Google Test framework
#
# https://github.com/google/googletest
#
P=OPAL
V=${OPAL_VERSION:-2021.1.0}

trap "otb_exit" EXIT

FNAME="$P-$V.tar.xz"
DOWNLOAD_URL="https://amas.web.psi.ch/Downloads/$P/src/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" \
    || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

# configure
mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
LDFLAFS='-lrt -ldl' cmake \
	-DCMAKE_INSTALL_PREFIX="${OTB_PREFIX}" \
        -DCMAKE_BUILD_TYPE=RELEASE \
	-DUSE_STATIC_LIBRARIES=ON \
	-DBUILD_OPAL_UNIT_TESTS=ON \
	-DENABLE_AMR=ON \
	-DENABLE_AMR_MG_SOLVER=ON \
	-DENABLE_BANDRF=ON \
	-DENABLE_IPPLTESTS=ON \
	-DENABLE_OPAL_FEL=ON \
	-DENABLE_SAAMG_SOLVER=ON \
	-DENABLE_MSLANG=ON \
	"${OTB_SRC_DIR}/$P/$P-$V" || exit ${OTB_ERR_CONFIGURE}

# compile and install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

