#!/bin/bash
#
# OPAL Toolchain Build recipe for the Google Test framework
#
# https://github.com/google/googletest
#
P=OPAL
V=${OPAL_VERSION:-2022.1.0}

trap "otb_exit" EXIT

FNAME="$P-$V.tar.xz"
DOWNLOAD_URL="https://amas.web.psi.ch/Downloads/$P/src/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
mkdir -p "${OTB_DOWNLOAD_DIR}"
test -r "${SRC_FILE}" \
    || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

# configure
mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}

# defaults
ENABLE_AMR=ON
ENABLE_AMR_MG_SOLVER=ON

# No Fortran on macOS with clang from Xcode
# :FIXME: in the future we might have flang!
if [[ "${OTB_TOOLSET}" == 'clang' ]] && [[ "${OTB_OS}" == 'macOS' ]]; then
	ENABLE_AMR='OFF'
	ENABLE_AMR_MG_SOLVER='OFF'
fi

export CC=mpicc
export CXX=mpicxx
export FC=mpifort
cmake \
	-DCMAKE_INSTALL_PREFIX="${OTB_PREFIX}" \
        -DCMAKE_BUILD_TYPE=RELEASE \
	-DUSE_STATIC_LIBRARIES=ON \
	-DBUILD_OPAL_UNIT_TESTS=ON \
	-DENABLE_AMR=${ENABLE_AMR} \
	-DENABLE_AMR_MG_SOLVER=${ENABLE_AMR_MG_SOLVER} \
	-DENABLE_BANDRF=ON \
	-DENABLE_IPPLTESTS=ON \
	-DENABLE_OPAL_FEL=ON \
	-DENABLE_SAAMG_SOLVER=ON \
	-DENABLE_MSLANG=ON \
	"${OTB_SRC_DIR}/$P/$P-$V" || exit ${OTB_ERR_CONFIGURE}

# compile and install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

