#!/bin/bash
#
# OPAL Toolchain Build recipe for the Google Test framework
#
# https://github.com/google/googletest
#
P=master
trap "otb_exit" EXIT

mkdir -p "${OTB_SRC_DIR}/OPAL/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
mkdir -p ${OTB_SRC_DIR}/OPAL/$P/bin

# defaults
ENABLE_AMR=OFF
ENABLE_AMR_MG_SOLVER=OFF

# No Fortran on macOS with clang from Xcode
# :FIXME: in the future we might have flang!
if [[ "${OTB_TOOLSET}" == 'clang' ]] && [[ "${OTB_OS}" == 'macOS' ]]; then
	ENABLE_AMR='OFF'
	ENABLE_AMR_MG_SOLVER='OFF'
fi
#        -DOPAL_CXX_FLAGS="-Wnon-c-typedef-for-linkage -Wnon-unused-but-set-variable" 
cd "${OTB_SRC_DIR}/OPAL/$P/build"
cmake \
    -DCMAKE_INSTALL_PREFIX="${OTB_SRC_DIR}/OPAL/$P/" \
    -DCMAKE_BUILD_TYPE=DEBUG \
	-DUSE_STATIC_LIBRARIES=ON \
	-DBUILD_OPAL_UNIT_TESTS=OFF \
	-DENABLE_AMR=${ENABLE_AMR} \
	-DENABLE_AMR_MG_SOLVER=${ENABLE_AMR_MG_SOLVER} \
	-DENABLE_BANDRF=ON \
	-DENABLE_IPPLTESTS=OFF \
	-DENABLE_OPAL_FEL=OFF \
	-DENABLE_SAAMG_SOLVER=OFF \
	-DENABLE_MSLANG=OFF \
	-DCMAKE_CXX_FLAGS="-w" \
	-DOPAL_CXX_FLAGS="-w" \
	.. || exit ${OTB_ERR_CONFIGURE}
NJOBS = 16
# compile and install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
#make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

