#!/bin/bash
P=ippl
build_type=${build_type:-serial}
ENABLE_FFT=${ENABLE_FFT:-ON}
ENABLE_SOLVERS=${ENABLE_SOLVERS:-ON}
ENABLE_ALPINE=${ENABLE_ALPINE:-ON}
ENABLE_UNIT_TESTS=${ENABLE_UNIT_TESTS:-ON}
NJOBS=8
trap "otb_exit" EXIT

# compiler="$(which mpicxx)"
CUDA=OFF
SERIAL=OFF
OPENMP=OFF
CXXFLAGS=""

build_mode=${build_mode:-Release}
compiler=${compiler:-"$(which gcc)"}

if [[ "$build_type" == "cuda" ]]; then
    echo "Build Cuda mode."
    compiler="${Kokkos_DIR}/bin/nvcc_wrapper"
    CXXFLAGS="--expt-relaxed-constexpr"
elif [[ "$build_type" == "serial" ]]; then
    echo "Build serial mode."
elif [[ "$build_type" == "openmp" ]]; then
    echo "Build OpenMP mode."
else
    echo "Wrong build type."
fi

cd "${OTB_SRC_DIR}"
if [ -d "ippl" ] 
then
    echo "Found existing IPPL source directory"
else
    echo "Clone ippl repo ... "
    git clone git@gitlab.psi.ch:OPAL/Libraries/ippl.git
fi

mkdir -p "${OTB_SRC_DIR}/$P/build_$build_type" && cd $_

cmake \
    -DCMAKE_BUILD_TYPE=${build_mode} \
    -DCMAKE_INSTALL_PREFIX=${OTB_PREFIX} \
    -DCMAKE_CXX_EXTENSIONS=OFF \
    -DENABLE_TESTS=ON \
    -DENABLE_UNIT_TESTS="${ENABLE_UNIT_TESTS}" \
    -DENABLE_FFT="${ENABLE_FFT}" \
    -DENABLE_SOLVERS="${ENABLE_SOLVERS}" \
    -DENABLE_ALPINE="${ENABLE_ALPINE}" \
    -DCMAKE_CXX_COMPILER=${compiler} \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    $ADDITIONAL_CMAKE_FLAGS \
    "${OTB_SRC_DIR}/$P"

# compile & install
make -j ${NJOBS}
make install
