#!/bin/bash

# recipe for:
P=mpfr
V=${MPFR_VERSION:=4.0.1}

# download
curl -L \
        --output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
        "http://www.mpfr.org/$P-$V/$P-$V.tar.gz"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install

