#!/bin/bash

# recipe for:
P=boost
V=${BOOST_VERSION:-1_68_0}

# download
test -r "${DOWNLOADS_DIR}/${P}_$V.tar.gz"  || \
        curl -L \
                --output "$_" \
                "https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${P}_$V.tar.gz"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/${P}_$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build"
cd "${SRC_DIR}/$P/${P}_$V"
./bootstrap.sh \
        --prefix="${PREFIX}" \
        --with-libraries=all

# compile & install
./b2 \
        --build-type=minimal \
        --build-dir=""${SRC_DIR}/$P/build"" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        stage
./b2 \
        --build-type=minimal \
        --build-dir=""${SRC_DIR}/$P/build"" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        install

