#!/bin/bash

# recipe for:
P=mpc
V=${MPC_VERSION:-1.1.0}

# download
test -r "${DOWNLOADS_DIR}/$P-$V.tar.gz" || \
        curl -L \
                --output "$_" \
                "ftp://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"

# unpack
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"

# configure
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --with-gmp="${PREFIX}" \
        --with-mpfr="${PREFIX}" \
        --disable-shared

# compile & install
make -j ${NJOBS}
make install

