#!/opt/local/bin/bash

if [[ -n "$1" ]]; then
        if [[ -d "$1" ]]; then
                OTB_PREFIX="$1"
        else
                echo -e "Passed prefix does not exist or is not a directory -- $1" 1>&2
		exit 1
	fi
fi
if [[ -z "${OTB_PREFIX}" ]]; then
	echo -e "OTB_PREFIX not set!\nAborting..." 1>&2
	exit 1
fi

#
# macOS specific post-install
#
postinstall_macOS() {

	########################################################
	#
	make_relocatable() {
		patch_exe() {
			#
			# - replace absolute path and relative
			#   path names with '@rpath' of
			#   dependent libraries with
			#   @executable_path/... 
			#
			local -r f="$1"
			local -r d="$2"

			# get list dependent libraries
			libs=( $(otool -L "$f" | awk \
					-v prefix="${OTB_PREFIX}" \
					'/^[[:space:]].*/ && (($1 ~ prefix) || ($1 ~ "@rpath")) {print $1}') )
			if [[ -z "${libs}" ]]; then
				return 0
			fi
			echo "post-processing executable: $f"
			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@executable_path/${str}lib"

			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing dependent shared library name from '$l' to '${new}'"
				install_name_tool -change "$l" "${new}" "$f"
			done
		}
		patch_lib() {
			#
			# - Change the id to
			#   @rpath/...
			# - Change dependent shared library install names to
			#   @loader_path/...
			#   if the name matches ${OTB_PREFIX} or @rpath
			#
			local -r f="$1"
			local -r d="$2"

			# check library id
			local lib_id=$(otool -D "$f" | grep -v "${f}:")
			local new_id=''
			[[ ${lib_id} =~ ^@rpath ]] || new_id="@rpath/${f##*/}"

			# get needed libs to be changed
			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@loader_path/${str}lib"
			libs=( $(otool -L "$f" | awk \
					-v prefix="${OTB_PREFIX}" -v lib="${f##*/}" \
					'(($1 ~ prefix) || ($1 ~ "@rpath")) && ($1 !~ lib) {print $1}') )

			if [[ -z "${new_id}" ]] && [[ -z "${libs}" ]]; then
			       return
			fi
			echo "post-processing library: $f"
			if [[ -n "${new_id}" ]]; then
				echo "    setting id to '${new_id}'"
				install_name_tool -id "${new_id}" "$f"
			fi
			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing dependent shared library name from '$l' to '${new}'"
				install_name_tool -change "$l"  "${new}" "$f"
			done
		}

		patch_bundle() {
			#
			# - Change dependent shared library install names to
			#   @loader_path/...
			#   if the name matches ${OTB_PREFIX} or @rpath
			#
			# please note:
			#	bundles do not have an id!
			#
			local -r f="$1"
			local -r d="$2"

			# get needed libs to be changed
			libs=( $(otool -L "$f" | awk \
					-v prefix="${OTB_PREFIX}" -v lib="${f##*/}" \
					'$0 ~ "^[[:space:]]/.*" && (($1 ~ prefix) || ($1 ~ "@rpath")) {print $1}') )
			if [[ -z "${libs}" ]]; then
				return 0
			fi
			echo "post-processing bundle: $f"
			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@loader_path/${str}lib"
			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing dependent shared library name from '$l' to '${new}'"
				install_name_tool -change "$l"  "${new}" "$f"
			done
		}

		#
		# check and patch all executables, libraries and bundles 
		# in ${OTB_PREFIX}/{bin,lib}
		#
		local -A executables
		local -A libraries
		local -- fname
		local -i depth
		echo "Check and patch executables, libraries and bundles..."
		while read depth fname; do
			case "$(file -b ${fname})" in
				Mach-O\ 64-bit\ executable\ * )
					patch_exe "${fname}" "${depth}"
					;;
				Mach-O\ 64-bit\ dynamically\ linked\ shared\ library\ * )
					patch_lib "${fname}" "${depth}"
					;;
				Mach-O\ 64-bit\ bundle\ * )
					patch_bundle "${fname}" "${depth}"
					;;
			esac
		done < <(gfind "${OTB_PREFIX}/bin" "${OTB_PREFIX}/lib" -type f -printf "%d %p\n" )
	}

	########################################################
	#
	# strip binaries
	#
	strip_unneeded() {
		while read depth fname; do
			case "$(file -b ${fname})" in
				Mach-O\ 64-bit\ executable\ * )
					strip -u -r "$fname"
					;;
				Mach-O\ 64-bit\ dynamically\ linked\ shared\ library\ * )
					strip -x "$fname"
					;;
				Mach-O\ 64-bit\ bundle\ * )
					:
					;;
			esac
		done < <(gfind "${OTB_PREFIX}/bin" "${OTB_PREFIX}/lib" -type f -printf "%d %p\n" )
	}

	########################################################
	#
	make_relocatable
	strip_unneeded
}

postinstall_macOS
