#!/opt/local/bin/bash

if [[ -n "$1" ]]; then
        if [[ -d "$1" ]]; then
                OTB_PREFIX="$1"
        else
                echo -e "Passed prefix does not exist or is not a directory -- $1" 1>&2
		exit 1
	fi
fi
if [[ -z "${OTB_PREFIX}" ]]; then
	echo -e "OTB_PREFIX not set!\nAborting..." 1>&2
	exit 1
fi

#
# macOS specific post-install
#
postinstall_macOS() {

	########################################################
	#
	make_relocatable() {
		patch_exe() {
			local -r f="$1"
			local -r d="$2"

			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@executable_path/${str}lib"

			# replace absolute paths of needed libraries
			libs=( $(otool -L "$f" | awk "  /${OTB_PREFIX//\//\\/}\/lib/ {print \$1}") )
			[[ -z "${libs}" ]] && return
			echo "post-process executable: $f"
			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing '$l' -> '${new}'"
				install_name_tool -change "$l" "${new}" "$f"
			done
		}
		patch_lib() {
			local -r f="$1"
			local -r d="$2"

			# check library id
			local lib_id=$(otool -D "$f" | grep -v "${f}:")
			local new_id=''
			[[ ${lib_id} =~ ^@rpath ]] || new_id="@rpath/${f##*/}"

			# get needed libs to be changed
			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@loader_path/${str}lib"
			libs=( $(otool -L "$f" | awk "/  ${OTB_PREFIX//\//\\/}\/lib/ {print \$1}") )

			if [[ -z "${new_id}" ]] && [[ -z "${libs}" ]]; then
			       return
			fi
			echo "post-process library: $f"
			if [[ -n "${new_id}" ]]; then
				echo "    setting id to '${new_id}'"
				install_name_tool -id "${new_id}" "$f"
			fi
			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing '$l' -> '${new}'"
				install_name_tool -change "$l"  "${new}" "$f"
			done
		}

		patch_bundle() {
			local -r f="$1"
			local -r d="$2"

			# get needed libs to be changed
			local str=$(printf "../%0.s" $(seq 1 $d))
			local path_prefix="@loader_path/${str}lib"
			libs=( $(otool -L "$f" | awk "/  ${OTB_PREFIX//\//\\/}\/lib/ {print \$1}") )

			if [[ -z "${libs}" ]]; then
			       return
			fi
			echo "post-process library: $f"
			for l in ${libs[*]}; do
				local new="${path_prefix}/${l##*/}"
				echo "    changing '$l' -> '${new}'"
				install_name_tool -change "$l"  "${new}" "$f"
			done
		}

		#
		# check and patch all executables, libraries and bundles 
		# in ${OTB_PREFIX}/{bin,lib}
		#
		local -A executables
		local -A libraries
		local -- fname
		local -i depth
		echo "Check and patch executables, libraries and bundles..."
		while read depth fname; do
			case "$(file -b ${fname})" in
				Mach-O\ 64-bit\ executable\ * )
					patch_exe "${fname}" "${depth}"
					;;
				Mach-O\ 64-bit\ dynamically\ linked\ shared\ library\ * )
					patch_lib "${fname}" "${depth}"
					;;
				Mach-O\ 64-bit\ bundle\ * )
					patch_bundle "${fname}" "${depth}"
					;;
			esac
		done < <(gfind "${OTB_PREFIX}/bin" "${OTB_PREFIX}/lib" -type f -printf "%d %p\n" )
	}

	########################################################
	#
	# strip binaries
	#
	strip_unneeded() {
		while read depth fname; do
			case "$(file -b ${fname})" in
				Mach-O\ 64-bit\ executable\ * )
					strip -u -r "$fname"
					;;
				Mach-O\ 64-bit\ dynamically\ linked\ shared\ library\ * )
					strip -x "$fname"
					;;
				Mach-O\ 64-bit\ bundle\ * )
					:
					;;
			esac
		done < <(gfind "${OTB_PREFIX}/bin" "${OTB_PREFIX}/lib" -type f -printf "%d %p\n" )
	}

	########################################################
	#
	make_relocatable
	strip_unneeded
}

postinstall_macOS
